In [1]:
import pandas as pd
import ast

In [225]:
data=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\delhi_cars.xlsx")
data

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1481,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1482,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1483,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1484,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

In [194]:
for i in data.columns:
    data[i]=data[i].map(eval)

In [195]:
df1=pd.DataFrame()
df1=pd.json_normalize(data['new_car_detail'])
df1

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [196]:
df2=pd.json_normalize(data['new_car_overview'])
df2

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Jan 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2017',...",None
...,...,...,...
1480,Car overview,"[{'key': 'Registration Year', 'value': '2019',...",None
1481,Car overview,"[{'key': 'Registration Year', 'value': '2021',...",None
1482,Car overview,"[{'key': 'Registration Year', 'value': '2011',...",None
1483,Car overview,"[{'key': 'Registration Year', 'value': 'Oct 20...",None
1484,Car overview,"[{'key': 'Insurance Validity', 'value': 'Third...",None

In [197]:
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df3

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO
0,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN
1,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51
2,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01
3,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C
4,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C
...,...,...,...,...,...,...,...,...,...,...
1480,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C
1481,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN
1482,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN
1483,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26
1484,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN

In [198]:
df4=pd.DataFrame()
df4=pd.json_normalize(data['new_car_feature'])
df4

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1481,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1482,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1483,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1484,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [199]:
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
df5

,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication
0,24,14,20,34,11
1,15,10,9,23,8
2,31,14,16,42,12
3,11,7,7,26,6
4,16,9,8,23,9
...,...,...,...,...,...
1480,26,11,11,28,9
1481,12,9,13,26,10
1482,16,11,9,25,5
1483,29,12,16,33,7
1484,29,13,20,32,12

In [200]:
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5

,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Features,Feature
0,24,14,20,34,11,{'Features': '9'},9
1,15,10,9,23,8,{'Features': '9'},9
2,31,14,16,42,12,{'Features': '9'},9
3,11,7,7,26,6,{'Features': '9'},9
4,16,9,8,23,9,{'Features': '9'},9
...,...,...,...,...,...,...,...
1480,26,11,11,28,9,{'Features': '9'},9
1481,12,9,13,26,10,{'Features': '9'},9
1482,16,11,9,25,5,{'Features': '9'},9
1483,29,12,16,33,7,{'Features': '9'},9
1484,29,13,20,32,12,{'Features': '9'},9

In [201]:
df5.drop('Features',axis=1,inplace=True)
df5

,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature
0,24,14,20,34,11,9
1,15,10,9,23,8,9
2,31,14,16,42,12,9
3,11,7,7,26,6,9
4,16,9,8,23,9,9
...,...,...,...,...,...,...
1480,26,11,11,28,9,9
1481,12,9,13,26,10,9
1482,16,11,9,25,5,9
1483,29,12,16,33,7,9
1484,29,13,20,32,12,9

In [202]:
df6=pd.json_normalize(data['new_car_specs'])
df6

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1480,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1481,Specifications,"[{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1482,Specifications,"[{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1483,Specifications,"[{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1484,Specifications,"[{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [203]:
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
df7

         Mileage   Engine  Max Power    Torque Wheel Size Seats
0        18 kmpl  1493 CC  113.43bhp     250Nm         17     5
1     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
2     12.74 kmpl  1991 CC     197bhp     320nm         19     5
3     22.38 kmpl  1197 CC   88.50bhp     113Nm        NaN     5
4     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
...          ...      ...        ...       ...        ...   ...
1480     18 kmpl  1497 CC   117.6bhp     145Nm         15     5
1481   18.4 kmpl  1197 CC   81.86bhp     115Nm        NaN     5
1482  17.01 kmpl  1591 CC   121.3bhp   154.9Nm         16     5
1483   20.5 kmpl  1582 CC   126.2bhp  259.87NM         17     5
1484  12.04 kmpl  1996 CC  212.55bhp   478.5Nm         19     6

[1485 rows x 6 columns]

In [204]:
a=pd.json_normalize(df6['data'])
a

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1480,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1481,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1482,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1483,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1484,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [205]:
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Gray'}, {'key': 'E..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
...,...,...,...
4450,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': 'CVT'}, {'key': ..."
4451,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
4452,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4453,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
4454,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8 Speed'}, {'ke..."

In [206]:
df['heading'].value_counts()

Engine and Transmission    1485
Miscellaneous              1485
Dimensions & Capacity      1484
Name: heading, dtype: int64

In [207]:
df8=df[df['heading'] =='Engine and Transmission']
df8

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Gray'}, {'key': 'E..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
...,...,...,...
1480,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1481,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1482,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1483,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
1484,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."

In [208]:
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df9

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Super Charger,BoreX Stroke,Compression Ratio
0,Gray,1.5 L CRDi VGT,1493,113.43bhp@4000rpm,250Nm@1500-2750rpm,4.0,4.0,CRDi,Yes,NaN,NaN,NaN,NaN
1,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN
2,Grey,M 264 petrol engine,1991,197bhp@5500-6100rpm,320nm@1650-4000rpm,4.0,4.0,EFI,No,NaN,NaN,NaN,NaN
3,Silver,K Series Dual jet,1197,88.50bhp@6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Others,i VTEC Engine,1497,117.6bhp@6600rpm,145Nm@4600rpm,4.0,4.0,PGM-Fi,No,SOHC,No,73.0 X 89.4 mm,10.3:1
1481,Others,SMARTSTREAM G1.2,1197,81.86bhp@6000rpm,115Nm@4200rpm,4.0,4.0,MPI,No,NaN,NaN,NaN,NaN
1482,Others,VTVT Petrol Engine,1591,121.3bhp@6300rpm,154.9Nm@4200rpm,4.0,4.0,MPFI,No,DOHC,No,77.0mm X 85.44mm,10.5;1
1483,Silver,U2 CRDI VGT Engine,1582,126.2bhp@4000rpm,259.87NM@1500-3000rpm,4.0,4.0,CRDi,Yes,DOHC,No,NaN,NaN
1484,Grey,DIESEL 2.0L TWIN TURBO,1996,212.55bhp@4000rpm,478.5Nm@1500-2400rpm,4.0,4.0,NaN,Twin,NaN,NaN,NaN,NaN

In [209]:
df10=df[df['heading'] =='Miscellaneous']
df10

,heading,subHeading,list
1670,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': 'Six Speed Manua..."
2970,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6-Speed'}, {'ke..."
2971,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
2972,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '9 speed Tronic'..."
2973,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
...,...,...,...
4450,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': 'CVT'}, {'key': ..."
4451,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
4452,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4453,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
4454,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8 Speed'}, {'ke..."

In [210]:
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df11

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn
0,Six Speed Manual with Paddle Shifter,All Wheel Drive,5,Power,5.3 Meter,Ventilated Discs,Drum in Discs,190kmph,11.5 seconds,"Tubeless,Radial",16,5,NaN
1,6-Speed,FWD,5,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",17,5,433
2,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,165 Kmph,10.5 Seconds,Tubeless,NaN,5,400-litres
3,9 speed Tronic,AWD,5,Power,NaN,Disc,Disc,217 Kmph,NaN,"Tubeless,Radial",19,5,550-litres
4,5-Speed,NaN,5,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,CVT,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,195 Kmph,10 Seconds,"Tubeless,Radial",15,4,510
1481,5-Speed,FWD,5,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",NaN,5,392
1482,5 Speed,FWD,5,Power,5.2 metres,Disc,Drum,196km/hr,10.5 Seconds,"Tubeless,Radial",16,4,465-litre
1483,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,160.58kmph,10.83 s,Tubeless,17,5,400
1484,8 Speed,4x4,6,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",19,5,NaN

In [211]:
df12=df[df['heading'] =='Dimensions & Capacity']
df12

,heading,subHeading,list
1485,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4315mm'}, {'key':..."
1486,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
1487,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4658mm'}, {'key':..."
1488,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3845mm'}, {'key':..."
1489,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
...,...,...,...
2965,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4440mm'}, {'key':..."
2966,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
2967,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4375mm'}, {'key':..."
2968,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
2969,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4985mm'}, {'key':..."

In [212]:
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)
df13

,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen
0,4315mm,1800mm,1645mm,2610mm,1540,NaN,NaN,NaN,NaN
1,4270mm,1780mm,1630mm,2590mm,"1,310",NaN,NaN,NaN,NaN
2,4658mm,1890mm,1644mm,2873mm,1585,2360kg,NaN,NaN,NaN
3,3845mm,1735,1530,2450,875-905,1335,1530,1530,NaN
4,4270mm,1780mm,1630mm,2590mm,"1,300",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1479,4440mm,1695mm,1495mm,2600mm,1080kg,1455kg,1490mm,1480mm,NaN
1480,3995mm,1790,1642,2500,1192,NaN,NaN,NaN,NaN
1481,4375mm,1700mm,1475mm,2570mm,1260,NaN,NaN,NaN,NaN
1482,4270mm,1780mm,1665mm,2590mm,1340,NaN,NaN,NaN,190mm
1483,4985mm,1926mm,1867mm,2950mm,2600,NaN,NaN,NaN,NaN

In [245]:
Data_Delhi=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
Data_Delhi

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Wheel Size,Seats,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Super Charger,BoreX Stroke,Compression Ratio,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN,24,14,20,34,11,9,18 kmpl,1493 CC,113.43bhp,250Nm,17,5,Gray,1.5 L CRDi VGT,1493,113.43bhp@4000rpm,250Nm@1500-2750rpm,4.0,4.0,CRDi,Yes,NaN,NaN,NaN,NaN,Six Speed Manual with Paddle Shifter,All Wheel Drive,5,Power,5.3 Meter,Ventilated Discs,Drum in Discs,190kmph,11.5 seconds,"Tubeless,Radial",16,5,NaN,4315mm,1800mm,1645mm,2610mm,1540,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51,15,10,9,23,8,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,5,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,6-Speed,FWD,5,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",17,5,433,4270mm,1780mm,1630mm,2590mm,"1,310",NaN,NaN,NaN,NaN
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01,31,14,16,42,12,9,12.74 kmpl,1991 CC,197bhp,320nm,19,5,Grey,M 264 petrol engine,1991,197bhp@5500-6100rpm,320nm@1650-4000rpm,4.0,4.0,EFI,No,NaN,NaN,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,165 Kmph,10.5 Seconds,Tubeless,NaN,5,400-litres,4658mm,1890mm,1644mm,2873mm,1585,2360kg,NaN,NaN,NaN
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C,11,7,7,26,6,9,22.38 kmpl,1197 CC,88.50bhp,113Nm,NaN,5,Silver,K Series Dual jet,1197,88.50bhp@6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9 speed Tronic,AWD,5,Power,NaN,Disc,Disc,217 Kmph,NaN,"Tubeless,Radial",19,5,550-litres,3845mm,1735,1530,2450,875-905,1335,1530,1530,NaN
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C,16,9,8,23,9,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,5,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,5-Speed,NaN,5,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268,4270mm,1780mm,1630mm,2590mm,"1,300",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C,26,11,11,28,9,9,18 kmpl,1497 CC,117.6bhp,145Nm,15,5,Others,i VTEC Engine,1497,117.6bhp@6600rpm,145Nm@4600rpm,4.0,4.0,PGM-Fi,No,SOHC,No,73.0 X 89.4 mm,10.3:1,CVT,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,195 Kmph,10 Seconds,"Tubeless,Radial",15,4,510,3995mm,1790,1642,2500,1192,NaN,NaN,NaN,NaN
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN,12,9,13,26,10,9,18.4 kmpl,1197 CC,81.86bhp,115Nm,NaN,5,Others,SMARTSTREAM G1.2,1197,81.86bhp@6000rpm,115Nm@4200rpm,4.0,4.0,MPI,No,NaN,NaN,NaN,NaN,5-Speed,FWD,5,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",NaN,5,392,4375mm,1700mm,1475mm,2570mm,1260,NaN,NaN,NaN,NaN
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN,16,11,9,25,5,9,17.01 kmpl,1591 CC,121.3bhp,154.9Nm,16,5,Others,VTVT Petrol Engine,1591,121.3bhp@6300rpm,154.9Nm@4200rpm,4.0,4.0,MPFI,No,DOHC,No,77.0mm X 85.44mm,10.5;1,5 Speed,FWD,5,Power,5.2 metres,Disc,Drum,196km/hr,10.5 Seconds,"Tubeless,Radial",16,4,465-litre,4270mm,1780mm,1665mm,2590mm,1340,NaN,NaN,NaN,190mm
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26,29,12,16,33,7,9,20.5 kmpl,1582 CC,126.2bhp,259.87NM,17,5,Silver,U2 CRDI VGT Engine,1582,126.2bhp@4000rpm,259.87NM@1500-3000rpm,4.0,4.0,CRDi,Yes,DOHC,No,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,160.58kmph,10.83 s,Tubeless,17,5,400,4985mm,1926mm,1867mm,2950mm,2600,NaN,NaN,NaN,NaN
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN,29,13,20,32,12,9,12.04 kmpl,1996 CC,212.55bhp,478.5Nm,19,6,Grey,DIESEL 2.0L TWIN TURBO,1996,212.55bhp@4000rpm,478.5Nm@1500-2400rpm,4.0,4.0,NaN,Twin,NaN,NaN,NaN,NaN,8 Speed,4x4,6,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [246]:
Data_Delhi['City']='Delhi'
Data_Delhi

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Wheel Size,Seats,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Super Charger,BoreX Stroke,Compression Ratio,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen,City
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN,24,14,20,34,11,9,18 kmpl,1493 CC,113.43bhp,250Nm,17,5,Gray,1.5 L CRDi VGT,1493,113.43bhp@4000rpm,250Nm@1500-2750rpm,4.0,4.0,CRDi,Yes,NaN,NaN,NaN,NaN,Six Speed Manual with Paddle Shifter,All Wheel Drive,5,Power,5.3 Meter,Ventilated Discs,Drum in Discs,190kmph,11.5 seconds,"Tubeless,Radial",16,5,NaN,4315mm,1800mm,1645mm,2610mm,1540,NaN,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51,15,10,9,23,8,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,5,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,6-Speed,FWD,5,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",17,5,433,4270mm,1780mm,1630mm,2590mm,"1,310",NaN,NaN,NaN,NaN,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01,31,14,16,42,12,9,12.74 kmpl,1991 CC,197bhp,320nm,19,5,Grey,M 264 petrol engine,1991,197bhp@5500-6100rpm,320nm@1650-4000rpm,4.0,4.0,EFI,No,NaN,NaN,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,165 Kmph,10.5 Seconds,Tubeless,NaN,5,400-litres,4658mm,1890mm,1644mm,2873mm,1585,2360kg,NaN,NaN,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C,11,7,7,26,6,9,22.38 kmpl,1197 CC,88.50bhp,113Nm,NaN,5,Silver,K Series Dual jet,1197,88.50bhp@6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9 speed Tronic,AWD,5,Power,NaN,Disc,Disc,217 Kmph,NaN,"Tubeless,Radial",19,5,550-litres,3845mm,1735,1530,2450,875-905,1335,1530,1530,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C,16,9,8,23,9,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,5,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,5-Speed,NaN,5,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268,4270mm,1780mm,1630mm,2590mm,"1,300",NaN,NaN,NaN,NaN,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C,26,11,11,28,9,9,18 kmpl,1497 CC,117.6bhp,145Nm,15,5,Others,i VTEC Engine,1497,117.6bhp@6600rpm,145Nm@4600rpm,4.0,4.0,PGM-Fi,No,SOHC,No,73.0 X 89.4 mm,10.3:1,CVT,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,195 Kmph,10 Seconds,"Tubeless,Radial",15,4,510,3995mm,1790,1642,2500,1192,NaN,NaN,NaN,NaN,Delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN,12,9,13,26,10,9,18.4 kmpl,1197 CC,81.86bhp,115Nm,NaN,5,Others,SMARTSTREAM G1.2,1197,81.86bhp@6000rpm,115Nm@4200rpm,4.0,4.0,MPI,No,NaN,NaN,NaN,NaN,5-Speed,FWD,5,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",NaN,5,392,4375mm,1700mm,1475mm,2570mm,1260,NaN,NaN,NaN,NaN,Delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN,16,11,9,25,5,9,17.01 kmpl,1591 CC,121.3bhp,154.9Nm,16,5,Others,VTVT Petrol Engine,1591,121.3bhp@6300rpm,154.9Nm@4200rpm,4.0,4.0,MPFI,No,DOHC,No,77.0mm X 85.44mm,10.5;1,5 Speed,FWD,5,Power,5.2 metres,Disc,Drum,196km/hr,10.5 Seconds,"Tubeless,Radial",16,4,465-litre,4270mm,1780mm,1665mm,2590mm,1340,NaN,NaN,NaN,190mm,Delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26,29,12,16,33,7,9,20.5 kmpl,1582 CC,126.2bhp,259.87NM,17,5,Silver,U2 CRDI VGT Engine,1582,126.2bhp@4000rpm,259.87NM@1500-3000rpm,4.0,4.0,CRDi,Yes,DOHC,No,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,160.58kmph,10.83 s,Tubeless,17,5,400,4985mm,1926mm,1867mm,2950mm,2600,NaN,NaN,NaN,NaN,Delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN,29,13,20,32,12,9,12.04 kmpl,1996 CC,212.55bhp,478.5Nm,19,6,Grey,DIESEL 2.0L TWIN TURBO,1996,212.55bhp@4000rpm,478.5Nm@1500-2400rpm,4.0,4.0,NaN,Twin,NaN,NaN,NaN,NaN,8 Speed,4x4,6,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi

# DUPLICATE COLUMNS

In [247]:
Data_Delhi.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [248]:
for i in Data_Delhi:
    print(i)
    print(Data_Delhi.columns.get_loc(i))

it
0
ft
1
bt
2
km
3
transmission
4
ownerNo
5
owner
6
oem
7
model
8
modelYear
9
centralVariantId
10
variantName
11
price
12
priceActual
13
priceSaving
14
priceFixedText
15
trendingText.imgUrl
16
trendingText.heading
17
trendingText.desc
18
Registration Year
19
Insurance Validity
20
Fuel Type
21
Seats
[False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Kms Driven
23
Ownership
24
Engine Displacement
25
Transmission
26
Year of Manufacture
27
RTO
28
Comfort & Convenience
29
Interior
30
Exterior
31
Safety
32
Entertainment & Communication
33
Feature
34
Mileage
35
Engine
36
Max Power
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Torque
38
Wheel Size
39
Seats
[False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Color
41
Engine Type
42
Displacement
43
Max Power
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Max Torque
45
No of Cylinder
46
Values per Cylinder
47
Fuel Suppy System
48
Turbo Charger
49
Value Configuration
50
Super Charger
51
BoreX Stroke
52
Compression Ratio
53
Gear Box
54
Drive Type
55
Seating Capacity
56
Steering Type
57
Turning Radius
58
Front Brake Type
59
Rear Brake Type
60
Top Speed
61
Acceleration
62
Tyre Type
63
Alloy Wheel Size
64
No Door Numbers
65
Cargo Volumn
66
Length
67
Width
68
Height
69
Wheel Base
70
Kerb Weight
71
Gross Weight
72
Front Tread
73
Rear Tread
74
Ground Clearance Unladen
75
City
76

In [249]:
Data_Delhi[Data_Delhi.columns[22]]

        Seats Seats
0     5 Seats     5
1     5 Seats     5
2     5 Seats     5
3     5 Seats     5
4     5 Seats     5
...       ...   ...
1480  5 Seats     5
1481  5 Seats     5
1482  5 Seats     5
1483  5 Seats     5
1484  6 Seats     6

[1485 rows x 2 columns]

In [250]:
Data_Delhi[Data_Delhi.columns[44]]

      Max Power            Max Power
0     113.43bhp    113.43bhp@4000rpm
1      121.3bhp     121.3bhp@6400rpm
2        197bhp  197bhp@5500-6100rpm
3      88.50bhp     88.50bhp@6000rpm
4      121.3bhp     121.3bhp@6400rpm
...         ...                  ...
1480   117.6bhp     117.6bhp@6600rpm
1481   81.86bhp     81.86bhp@6000rpm
1482   121.3bhp     121.3bhp@6300rpm
1483   126.2bhp     126.2bhp@4000rpm
1484  212.55bhp    212.55bhp@4000rpm

[1485 rows x 2 columns]

In [251]:
column_indices_to_change={44:'RPM'}
Data_Delhi.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(Data_Delhi.columns)]
rpm=[]
for i in Data_Delhi['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
rpm
Data_Delhi['RPM']=rpm

In [252]:
Data_Delhi.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [253]:
for i in Data_Delhi:
    print(i)
    print(Data_Delhi.columns.get_loc(i))

it
0
ft
1
bt
2
km
3
transmission
4
ownerNo
5
owner
6
oem
7
model
8
modelYear
9
centralVariantId
10
variantName
11
price
12
priceActual
13
priceSaving
14
priceFixedText
15
trendingText.imgUrl
16
trendingText.heading
17
trendingText.desc
18
Registration Year
19
Insurance Validity
20
Fuel Type
21
Seats
[False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Kms Driven
23
Ownership
24
Engine Displacement
25
Transmission
26
Year of Manufacture
27
RTO
28
Comfort & Convenience
29
Interior
30
Exterior
31
Safety
32
Entertainment & Communication
33
Feature
34
Mileage
35
Engine
36
Max Power
37
Torque
38
Wheel Size
39
Seats
[False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
Color
41
Engine Type
42
Displacement
43
RPM
44
Max Torque
45
No of Cylinder
46
Values per Cylinder
47
Fuel Suppy System
48
Turbo Charger
49
Value Configuration
50
Super Charger
51
BoreX Stroke
52
Compression Ratio
53
Gear Box
54
Drive Type
55
Seating Capacity
56
Steering Type
57
Turning Radius
58
Front Brake Type
59
Rear Brake Type
60
Top Speed
61
Acceleration
62
Tyre Type
63
Alloy Wheel Size
64
No Door Numbers
65
Cargo Volumn
66
Length
67
Width
68
Height
69
Wheel Base
70
Kerb Weight
71
Gross Weight
72
Front Tread
73
Rear Tread
74
Ground Clearance Unladen
75
City
76

In [254]:
Data_Delhi=Data_Delhi.loc[:,~Data_Delhi.columns.duplicated()]

In [255]:
Data_Delhi.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [256]:
Data_Delhi

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Wheel Size,Color,Engine Type,Displacement,RPM,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Super Charger,BoreX Stroke,Compression Ratio,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen,City
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN,24,14,20,34,11,9,18 kmpl,1493 CC,113.43bhp,250Nm,17,Gray,1.5 L CRDi VGT,1493,4000rpm,250Nm@1500-2750rpm,4.0,4.0,CRDi,Yes,NaN,NaN,NaN,NaN,Six Speed Manual with Paddle Shifter,All Wheel Drive,5,Power,5.3 Meter,Ventilated Discs,Drum in Discs,190kmph,11.5 seconds,"Tubeless,Radial",16,5,NaN,4315mm,1800mm,1645mm,2610mm,1540,NaN,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51,15,10,9,23,8,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,White,VTVT Petrol Engine,1591,6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,6-Speed,FWD,5,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",17,5,433,4270mm,1780mm,1630mm,2590mm,"1,310",NaN,NaN,NaN,NaN,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01,31,14,16,42,12,9,12.74 kmpl,1991 CC,197bhp,320nm,19,Grey,M 264 petrol engine,1991,5500-6100rpm,320nm@1650-4000rpm,4.0,4.0,EFI,No,NaN,NaN,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,165 Kmph,10.5 Seconds,Tubeless,NaN,5,400-litres,4658mm,1890mm,1644mm,2873mm,1585,2360kg,NaN,NaN,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C,11,7,7,26,6,9,22.38 kmpl,1197 CC,88.50bhp,113Nm,NaN,Silver,K Series Dual jet,1197,6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9 speed Tronic,AWD,5,Power,NaN,Disc,Disc,217 Kmph,NaN,"Tubeless,Radial",19,5,550-litres,3845mm,1735,1530,2450,875-905,1335,1530,1530,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C,16,9,8,23,9,9,15.29 kmpl,1591 CC,121.3bhp,151Nm,NaN,White,VTVT Petrol Engine,1591,6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN,5-Speed,NaN,5,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268,4270mm,1780mm,1630mm,2590mm,"1,300",NaN,NaN,NaN,NaN,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C,26,11,11,28,9,9,18 kmpl,1497 CC,117.6bhp,145Nm,15,Others,i VTEC Engine,1497,6600rpm,145Nm@4600rpm,4.0,4.0,PGM-Fi,No,SOHC,No,73.0 X 89.4 mm,10.3:1,CVT,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,195 Kmph,10 Seconds,"Tubeless,Radial",15,4,510,3995mm,1790,1642,2500,1192,NaN,NaN,NaN,NaN,Delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN,12,9,13,26,10,9,18.4 kmpl,1197 CC,81.86bhp,115Nm,NaN,Others,SMARTSTREAM G1.2,1197,6000rpm,115Nm@4200rpm,4.0,4.0,MPI,No,NaN,NaN,NaN,NaN,5-Speed,FWD,5,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",NaN,5,392,4375mm,1700mm,1475mm,2570mm,1260,NaN,NaN,NaN,NaN,Delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN,16,11,9,25,5,9,17.01 kmpl,1591 CC,121.3bhp,154.9Nm,16,Others,VTVT Petrol Engine,1591,6300rpm,154.9Nm@4200rpm,4.0,4.0,MPFI,No,DOHC,No,77.0mm X 85.44mm,10.5;1,5 Speed,FWD,5,Power,5.2 metres,Disc,Drum,196km/hr,10.5 Seconds,"Tubeless,Radial",16,4,465-litre,4270mm,1780mm,1665mm,2590mm,1340,NaN,NaN,NaN,190mm,Delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26,29,12,16,33,7,9,20.5 kmpl,1582 CC,126.2bhp,259.87NM,17,Silver,U2 CRDI VGT Engine,1582,4000rpm,259.87NM@1500-3000rpm,4.0,4.0,CRDi,Yes,DOHC,No,NaN,NaN,6 Speed,FWD,5,Power,5.3 metres,Disc,Drum,160.58kmph,10.83 s,Tubeless,17,5,400,4985mm,1926mm,1867mm,2950mm,2600,NaN,NaN,NaN,NaN,Delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN,29,13,20,32,12,9,12.04 kmpl,1996 CC,212.55bhp,478.5Nm,19,Grey,DIESEL 2.0L TWIN TURBO,1996,4000rpm,478.5Nm@1500-2400rpm,4.0,4.0,NaN,Twin,NaN,NaN,NaN,NaN,8 Speed,4x4,6,Electric,NaN,Disc,Disc,NaN,NaN,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi

# BANGALORE DATASET

In [24]:
data_Blore=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\bangalore_cars.xlsx")
data_Blore

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [25]:
data_Blore.drop('car_links',axis=1,inplace=True)

In [26]:
for i in data_Blore.columns:
    data_Blore[i]=data_Blore[i].map(eval)

In [27]:
df1=pd.DataFrame()
df1=pd.json_normalize(data_Blore['new_car_detail'])
df2=pd.DataFrame()
df2=pd.json_normalize(data_Blore['new_car_overview'])
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df4=pd.DataFrame()
df4=pd.json_normalize(data_Blore['new_car_feature'])
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5.drop('Features',axis=1,inplace=True)
df6=pd.json_normalize(data_Blore['new_car_specs'])
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
a=pd.json_normalize(df6['data'])
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df['heading'].value_counts()
df8=df[df['heading'] =='Engine and Transmission']
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df10=df[df['heading'] =='Miscellaneous']
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df12=df[df['heading'] =='Dimensions & Capacity']
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)

data_Blore=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
data_Blore['City']='Bangalore'

In [262]:
pd.set_option('display.max_columns',10)

In [84]:
data_Blore

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Seats,Wheel Size,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Gear Box,Drive Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Cargo Volumn,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0,10,7,5,13,NaN,8,23.1 kmpl,998 CC,67.04bhp,90Nm,5,NaN,White,K10B Engine,998,67.04bhp@6000rpm,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,6,Power,"Tubeless,Radial",15,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0,17,12,12,27,9,9,17 kmpl,1497 CC,121.31bhp,150Nm,5,16,White,Ti-VCT Petrol Engine,1497,121.31bhp@6500rpm,150Nm@4500rpm,3.0,4.0,DOHC,Direct Injection,79 X 76.5 mm,11.0:1,No,No,8,Power,"Tubeless,Radial",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,â‚¹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0,14,12,13,24,8,9,23.84 kmpl,1199 CC,84bhp,114Nm,5,14,Red,Revotron Engine,1199,84bhp@6000rpm,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,â‚¹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0,16,10,10,18,7,9,19.1 kmpl,1197 CC,81.86bhp,113.75Nm,5,14,Others,Kappa VTVT Petrol Engine,1197,81.86bhp@6000rpm,113.75Nm@4000rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,No,No,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,â‚¹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0,21,11,13,22,8,9,23.65 kmpl,1248 CC,88.5bhp,200Nm,5,16,Gray,DDiS 200 Diesel Engine,1248,88.5bhp@4000rpm,200Nm@1750rpm,4.0,4.0,DOHC,NaN,69.6 x 82 mm,NaN,Yes,No,5,Power,"Tubeless,Radial",13,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,â‚¹ 16.49 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2012,Comprehensive,Diesel,7 Seats,"1,56,039 Kms",KA01,Second Owner,2982 cc,Manual,2012.0,19,11,12,26,10,9,12.55 kmpl,2982 CC,168.5bhp,343Nm,7,17,White,i-VTEC Engine,1198,86.8bhp@6000rpm,109Nm@4500rpm,4.0,4.0,SOHC,PGM - Fi,NaN,NaN,No,No,5,Power,"Tubeless, Radial",16,4,5 Speed,NaN,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,505 litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,â‚¹ 3.30 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Jun 2008,Third Party insurance,Petrol,5 Seats,"56,000 Kms",KA02,Second Owner,1586 cc,Manual,2008.0,16,12,6,19,5,9,15 kmpl,1586 CC,104.68,145,5,16,Red,U2 CRDI Diesel Engine,1396,88.73bhp@4000rpm,219.7Nm@1500-2750rpm,4.0,4.0,DOHC,CRDI,NaN,NaN,Yes,No,5,Power,"Tubeless,Radial",NaN,5,5 Speed,FWD,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,175-litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,â‚¹ 4.25 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Sept 2014,Comprehensive,Petrol,5 Seats,"42,000 Kms",KA03,Second Owner,1198 cc,Manual,2014.0,12,10,6,16,5,9,19.4 kmpl,1198 CC,86.8bhp,109Nm,5,NaN,White,Kappa VTVT Petrol Engine,1197,82bhp@6000rpm,114Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,5,Power,Tubeless,16,5,6 Speed,FWD,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,295-litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,â‚¹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2018,Comprehensive,Diesel,5 Seats,"93,003 Kms",KA03,First Owner,1396 cc,Manual,2018.0,19,11,11,26,9,9,22.54 kmpl,1396 CC,88.73bhp,219.7Nm,5,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Power,Tubeless,14,5,4 Speed,FWD,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,256-liters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,â‚¹ 6.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2017,Comprehensive,Petrol,5 Seats,"36,000 Kms",KA04,Second Owner,1197 cc,Automatic,2017.0,15,11,14,20,7,9,18.9 kmpl,1197 CC,82bhp,114Nm,5,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore

# HANDLING DUPLICATE COLUMNS

In [257]:
column_indices_to_change={44:'RPM'}
data_Blore.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(data_Blore.columns)]
data_Blore['RPM']
rpm=[]
for i in data_Blore['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
data_Blore['RPM']=rpm
data_Blore=data_Blore.loc[:,~data_Blore.columns.duplicated()]

In [258]:
data_Blore

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Wheel Size,Color,Engine Type,Displacement,RPM,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Gear Box,Drive Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Cargo Volumn,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0,10,7,5,13,NaN,8,23.1 kmpl,998 CC,67.04bhp,90Nm,NaN,White,K10B Engine,998,NA,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,6,Power,"Tubeless,Radial",15,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0,17,12,12,27,9,9,17 kmpl,1497 CC,121.31bhp,150Nm,16,White,Ti-VCT Petrol Engine,1497,NA,150Nm@4500rpm,3.0,4.0,DOHC,Direct Injection,79 X 76.5 mm,11.0:1,No,No,8,Power,"Tubeless,Radial",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,â‚¹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0,14,12,13,24,8,9,23.84 kmpl,1199 CC,84bhp,114Nm,14,Red,Revotron Engine,1199,NA,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,â‚¹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0,16,10,10,18,7,9,19.1 kmpl,1197 CC,81.86bhp,113.75Nm,14,Others,Kappa VTVT Petrol Engine,1197,NA,113.75Nm@4000rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,No,No,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,â‚¹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0,21,11,13,22,8,9,23.65 kmpl,1248 CC,88.5bhp,200Nm,16,Gray,DDiS 200 Diesel Engine,1248,NA,200Nm@1750rpm,4.0,4.0,DOHC,NaN,69.6 x 82 mm,NaN,Yes,No,5,Power,"Tubeless,Radial",13,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,â‚¹ 16.49 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2012,Comprehensive,Diesel,7 Seats,"1,56,039 Kms",KA01,Second Owner,2982 cc,Manual,2012.0,19,11,12,26,10,9,12.55 kmpl,2982 CC,168.5bhp,343Nm,17,White,i-VTEC Engine,1198,NA,109Nm@4500rpm,4.0,4.0,SOHC,PGM - Fi,NaN,NaN,No,No,5,Power,"Tubeless, Radial",16,4,5 Speed,NaN,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,505 litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,â‚¹ 3.30 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Jun 2008,Third Party insurance,Petrol,5 Seats,"56,000 Kms",KA02,Second Owner,1586 cc,Manual,2008.0,16,12,6,19,5,9,15 kmpl,1586 CC,104.68,145,16,Red,U2 CRDI Diesel Engine,1396,NA,219.7Nm@1500-2750rpm,4.0,4.0,DOHC,CRDI,NaN,NaN,Yes,No,5,Power,"Tubeless,Radial",NaN,5,5 Speed,FWD,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,175-litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,â‚¹ 4.25 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Sept 2014,Comprehensive,Petrol,5 Seats,"42,000 Kms",KA03,Second Owner,1198 cc,Manual,2014.0,12,10,6,16,5,9,19.4 kmpl,1198 CC,86.8bhp,109Nm,NaN,White,Kappa VTVT Petrol Engine,1197,NA,114Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,5,Power,Tubeless,16,5,6 Speed,FWD,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,295-litres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,â‚¹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Dec 2018,Comprehensive,Diesel,5 Seats,"93,003 Kms",KA03,First Owner,1396 cc,Manual,2018.0,19,11,11,26,9,9,22.54 kmpl,1396 CC,88.73bhp,219.7Nm,16,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Power,Tubeless,14,5,4 Speed,FWD,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,256-liters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,â‚¹ 6.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,May 2017,Comprehensive,Petrol,5 Seats,"36,000 Kms",KA04,Second Owner,1197 cc,Automatic,2017.0,15,11,14,20,7,9,18.9 kmpl,1197 CC,82bhp,114Nm,14,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore

# HYDERABAD DATASET

In [29]:
data_hyderabad=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\hyderabad_cars.xlsx")
data_hyderabad

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1478,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [30]:
data_hyderabad.drop('car_links',axis=1,inplace=True)

In [31]:
for i in data_hyderabad.columns:
    data_hyderabad[i]=data_hyderabad[i].map(eval)

In [32]:
df1=pd.DataFrame()
df1=pd.json_normalize(data_hyderabad['new_car_detail'])
df2=pd.json_normalize(data_hyderabad['new_car_overview'])
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df4=pd.DataFrame()
df4=pd.json_normalize(data_hyderabad['new_car_feature'])
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5.drop('Features',axis=1,inplace=True)
df6=pd.json_normalize(data_hyderabad['new_car_specs'])
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
a=pd.json_normalize(df6['data'])
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df['heading'].value_counts()
df8=df[df['heading'] =='Engine and Transmission']
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df10=df[df['heading'] =='Miscellaneous']
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df12=df[df['heading'] =='Dimensions & Capacity']
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)

data_hyderabad=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
data_hyderabad['City']='Hyderabad'

In [33]:
data_hyderabad

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,3971mm,1682mm,1469mm,2470mm,1457mm,1500mm,1106,1570,NaN,Hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,3495mm,1550mm,1500mm,2380mm,1386mm,1368mm,880,NaN,NaN,Hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,3995mm,1770mm,1617mm,2500mm,NaN,NaN,1106,NaN,NaN,Hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,3995mm,1745mm,1510mm,2520mm,1505mm,1515mm,890Kg,1340kg,NaN,Hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,3985mm,1855mm,1844mm,2450mm,1520mm,1520mm,1825,NaN,NaN,Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad

In [259]:
column_indices_to_change={44:'RPM'}
data_hyderabad.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(data_hyderabad.columns)]
data_hyderabad['RPM']
rpm=[]
for i in data_hyderabad['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
data_hyderabad['RPM']=rpm
data_hyderabad=data_hyderabad.loc[:,~data_hyderabad.columns.duplicated()]

In [261]:
data_hyderabad

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Feature,Mileage,Engine,Max Power,Torque,Wheel Size,Color,Engine Type,Displacement,RPM,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Gear Box,Drive Type,Turning Radius,Front Brake Type,Rear Brake Type,Cargo Volumn,Top Speed,Acceleration,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,7746,1.0 TSI Highline Plus AT,â‚¹ 10.44 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",TS04,First Owner,999 cc,Automatic,2022.0,18,13,15,30,10,9,16.47 kmpl,999 CC,108.62bhp,175nm,R16,Others,1.0L TSI Petrol,999,5000-5500rpm,175nm@1750-4000rpm,3.0,4.0,DOHC,TSI,74.5x76.4 mm,10.5:1,Yes,No,5,Power,"Tubeless,Radial",16,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3971mm,1682mm,1469mm,2470mm,1457mm,1500mm,1106,1570,NaN,Hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,1502,Era Plus,â‚¹ 2.60 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Oct 2014,Third Party insurance,Petrol,5 Seats,"85,582 Kms",TS09,Second Owner,814 cc,Manual,2014.0,9,6,6,13,NaN,8,21.1 kmpl,814 CC,55.2bhp,74.5Nm,NaN,Red,Petrol Engine,814,5500rpm,74.5Nm@4000rpm,3.0,3.0,SOHC,MPFI,NaN,NaN,No,No,6,Power,"Tubeless,Radial",15,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3495mm,1550mm,1500mm,2380mm,1386mm,1368mm,880,NaN,NaN,Hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,9153,S BSVI,â‚¹ 9.55 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2023,Third Party insurance,Petrol,5 Seats,"10,000 Kms",NaN,First Owner,1197 cc,Manual,2023.0,12,9,8,29,9,9,NaN,1197 CC,81.80bhp,113.8Nm,NaN,Others,1.2 Kappa Petrol,1197,6000rpm,113.8Nm@4000rpm,4.0,4.0,NaN,NaN,NaN,NaN,No,NaN,8,Power,"Tubeless,Radial",14,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3995mm,1770mm,1617mm,2500mm,NaN,NaN,1106,NaN,NaN,Hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,3970,1.2 Alpha,â‚¹ 6.71 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Mar 2017,Third Party insurance,Petrol,5 Seats,"50,750 Kms",TS07,First Owner,1197 cc,Manual,2017.0,15,12,13,28,9,9,21.4 kmpl,1197 CC,83.1bhp,115Nm,16,Red,VVT Petrol Engine,1197,6000rpm,115Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3995mm,1745mm,1510mm,2520mm,1505mm,1515mm,890Kg,1340kg,NaN,Hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,8074,LX 4-Str Hard Top AT BSVI,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2022,Third Party insurance,Petrol,4 Seats,"10,000 Kms",NaN,First Owner,1997 cc,Automatic,2022.0,12,10,7,24,9,9,NaN,1997 CC,150bhp,320Nm,18,Others,mStallion 150 TGDi Engine,1997,5000rpm,320Nm@1500-3000rpm,4.0,4.0,NaN,NaN,NaN,NaN,Yes,NaN,5,Power,"Tubeless,Radial",13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3985mm,1855mm,1844mm,2450mm,1520mm,1520mm,1825,NaN,NaN,Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,3823,W8 2WD,â‚¹ 7 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2013,Third Party insurance,Diesel,7 Seats,"60,000 Kms",TS09,First Owner,2179 cc,Manual,2013.0,17,11,12,22,6,9,15.1 kmpl,2179 CC,140bhp,330Nm,17,Blue,Diesel S Engine,2993,4000rpm,600Nm@2000rpm,6.0,4.0,DOHC,Direct Injection,NaN,NaN,Yes,No,7,Power,"Tubeless,Radial",17,5,6 Speed,FWD,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,NaN,175 kmph,12.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,5007,3.0 Litre S Premium Luxury,â‚¹ 20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2014,Third Party insurance,Diesel,5 Seats,"50,000 Kms",NaN,First Owner,2993 cc,Automatic,2014.0,23,14,12,29,9,9,14.74 kmpl,2993 CC,270.9bhp,600Nm,20,Blue,TwinPower Turbo Inline 4 Cylinder Engine,1995,4000rpm,400Nm@1750-2500rpm,4.0,4.0,NaN,CRDi,NaN,NaN,Twin,No,5,Power,"Tubeless,Radial",20,4,8 Speed,RWD,5.75 metres,Disc,Disc,540-litres,250 Kmph,6.4 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,250,520d Luxury Line,â‚¹ 35 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2018,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",TS09,Third Owner,1995 cc,Automatic,2018.0,29,15,20,37,13,9,20.37 kmpl,1995 CC,187.74bhp,400Nm,R18,Others,"Revotorq, 1.5L Turbocharged engine",1497,3750rpm,260Nm@1500-2750rpm,4.0,4.0,DOHC,CDI,76x82.5,NaN,Yes,No,5,Power,"Tubeless, Runflat",R18,4,8-Speed Steptronic,RWD,5.6,Ventilated Disc,Ventilated Disc,520-litres,235kmph,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,6500,1.5 Revotorq XMA,â‚¹ 8.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2019,Third Party insurance,Diesel,5 Seats,"50,000 Kms",TS08,Second Owner,1497 cc,Automatic,2019.0,10,11,6,22,6,9,21.5 kmpl,1497 CC,108.5bhp,260Nm,NaN,Others,2KD-FTV Diesel Engine,2494,3600rpm,200Nm@1200-3600rpm,4.0,4.0,DOHC,CRDi,NaN,NaN,Yes,No,5,Power,Tubeless Radial Tyres,NaN,5,6 Speed,FWD,5.1m,Disc,Drum,350,154.19 kmph,13.25 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,2294,2.5 ZX Diesel 7 Seater,â‚¹ 15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,2015,Third Party insurance,Diesel,7 Seats,"1,00,000 Kms",NaN,First Owner,2494 cc,Manual,2015.0,13,12,11,22,10,9,12.99 kmpl,2494 CC,100.6bhp,200Nm,15,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,Power,"Tubeless,Radial",15,5,5 Speed,RWD,5.4 metres,Ventilated Disc,Drum,300-litres,155 Kmph,13.3 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad

# CHENNAI DATASET

In [34]:
data_Chennai=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\chennai_cars.xlsx")
data_Chennai

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [35]:
data_Chennai.drop('car_links',axis=1,inplace=True)

In [36]:
for i in data_Chennai.columns:
    data_Chennai[i]=data_Chennai[i].map(eval)

In [37]:
df1=pd.DataFrame()
df1=pd.json_normalize(data_Chennai['new_car_detail'])
df2=pd.json_normalize(data_Chennai['new_car_overview'])
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df4=pd.DataFrame()
df4=pd.json_normalize(data_Chennai['new_car_feature'])
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5.drop('Features',axis=1,inplace=True)
df6=pd.json_normalize(data_Chennai['new_car_specs'])
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
a=pd.json_normalize(df6['data'])
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df['heading'].value_counts()
df8=df[df['heading'] =='Engine and Transmission']
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df10=df[df['heading'] =='Miscellaneous']
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df12=df[df['heading'] =='Dimensions & Capacity']
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)

data_Chennai=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
data_Chennai['City']='Chennai'

In [38]:
data_Chennai

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Length,Width,Height,Wheel Base,Kerb Weight,Front Tread,Rear Tread,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,3995mm,1790,1642,2500,1465,NaN,NaN,NaN,NaN,Chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,3675mm,1475mm,1800mm,2350mm,943kg,1280mm,1290mm,1540kg,NaN,Chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,3994mm,1758,1572,2500,1014,NaN,NaN,NaN,NaN,Chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,3585mm,1595mm,1550mm,2380mm,860kg,1400mm,1385mm,NaN,NaN,Chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,3955mm,1694mm,1544mm,2530mm,1042kg,NaN,NaN,NaN,NaN,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai

# HANDLING DUPLICATE COLUMNS

In [263]:
column_indices_to_change={44:'RPM'}
data_Chennai.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(data_Chennai.columns)]
data_Chennai['RPM']
rpm=[]
for i in data_Chennai['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
data_Chennai['RPM']=rpm
data_Chennai=data_Chennai.loc[:,~data_Chennai.columns.duplicated()]

In [264]:
data_Chennai

,it,ft,bt,km,transmission,...,Front Tread,Rear Tread,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,SUV,"20,000",Automatic,...,NaN,NaN,NaN,NaN,Chennai
1,0,Petrol,Minivans,"20,687",Manual,...,1280mm,1290mm,1540kg,NaN,Chennai
2,0,Petrol,SUV,"30,000",Manual,...,NaN,NaN,NaN,NaN,Chennai
3,0,Petrol,Hatchback,"59,247",Manual,...,1400mm,1385mm,NaN,NaN,Chennai
4,0,Petrol,Hatchback,"50,000",Manual,...,NaN,NaN,NaN,NaN,Chennai
...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,...,NaN,NaN,NaN,NaN,Chennai
1415,0,Diesel,SUV,"59,100",Manual,...,NaN,NaN,NaN,NaN,Chennai
1416,0,Petrol,SUV,"55,913",Automatic,...,NaN,NaN,NaN,NaN,Chennai
1417,0,Diesel,SUV,"65,000",Automatic,...,NaN,NaN,NaN,NaN,Chennai
1418,0,Diesel,Sedan,"60,000",Automatic,...,NaN,NaN,NaN,NaN,Chennai

# JAIPUR DATASET

In [39]:
data_Jaipur=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\jaipur_cars.xlsx")
data_Jaipur

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1115,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1116,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1117,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1118,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1119,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [40]:
data_Jaipur.drop('car_links',axis=1,inplace=True)

In [41]:
for i in data_Jaipur.columns:
    data_Jaipur[i]=data_Jaipur[i].map(eval)

In [42]:
df1=pd.DataFrame()
df1=pd.json_normalize(data_Jaipur['new_car_detail'])
df2=pd.json_normalize(data_Jaipur['new_car_overview'])
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df4=pd.DataFrame()
df4=pd.json_normalize(data_Jaipur['new_car_feature'])
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5.drop('Features',axis=1,inplace=True)
df6=pd.json_normalize(data_Jaipur['new_car_specs'])
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
a=pd.json_normalize(df6['data'])
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df['heading'].value_counts()
df8=df[df['heading'] =='Engine and Transmission']
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df10=df[df['heading'] =='Miscellaneous']
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df12=df[df['heading'] =='Dimensions & Capacity']
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)

data_Jaipur=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
data_Jaipur['City']='Jaipur'

In [43]:
data_Jaipur

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,3985mm,1734mm,1505mm,2570mm,1505mm,1503mm,1515kg,NaN,NaN,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,3845mm,1735,1530,2450,1530,1530,875-905,1335,NaN,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,840kg,1250kg,NaN,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,3765mm,1660mm,1520mm,2425mm,1479mm,1493mm,1100,NaN,NaN,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,3599mm,1495mm,1700mm,2400mm,1295mm,1290mm,890kg,1350kg,NaN,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur

# HANDLING DUPLICATE COLUMNS

In [265]:
column_indices_to_change={44:'RPM'}
data_Jaipur.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(data_Jaipur.columns)]
data_Jaipur['RPM']
rpm=[]
for i in data_Jaipur['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
data_Jaipur['RPM']=rpm
data_Jaipur=data_Jaipur.loc[:,~data_Jaipur.columns.duplicated()]

In [266]:
data_Jaipur

,it,ft,bt,km,transmission,...,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Diesel,Hatchback,"1,20,000",Manual,...,1503mm,1515kg,NaN,NaN,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,...,1530,875-905,1335,NaN,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,...,1410mm,840kg,1250kg,NaN,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,...,1493mm,1100,NaN,NaN,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,...,1290mm,890kg,1350kg,NaN,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,...,NaN,NaN,NaN,NaN,Jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,...,NaN,NaN,NaN,NaN,Jaipur
1117,0,Petrol,SUV,"20,000",Manual,...,NaN,NaN,NaN,NaN,Jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,...,NaN,NaN,NaN,NaN,Jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,...,NaN,NaN,NaN,NaN,Jaipur

# KOLKATA DATASET

In [44]:
data_Kolkata=pd.read_excel(r"C:\Users\DELL\Documents\Guvi\Capstone Project 3\kolkata_cars.xlsx")
data_Kolkata

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [45]:
data_Kolkata.drop('car_links',axis=1,inplace=True)

In [46]:
for i in data_Kolkata.columns:
    data_Kolkata[i]=data_Kolkata[i].map(eval)
df1=pd.DataFrame()
df1=pd.json_normalize(data_Kolkata['new_car_detail'])
df2=pd.json_normalize(data_Kolkata['new_car_overview'])
df3=pd.DataFrame()
for i in df2['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df3=pd.concat([df3,a],ignore_index=True)
df4=pd.DataFrame()
df4=pd.json_normalize(data_Kolkata['new_car_feature'])
df5=pd.DataFrame()
for i in df4['data']:
    res=pd.json_normalize(i)
    keys=[]
    values=[]
    if len(res)>0:
        for i in res['heading']:
            keys.append(i)
        for i in res['list']:
            v=[]
            for j in i:
                v.append(j.get('value'))
            values.append(str(len(v)))
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
    else:
        values='None'
        result=dict(zip(keys,values))
        results=pd.json_normalize(result)
        df5=pd.concat([df5,results],ignore_index=True)
key=[]
Feature=[]
for i,j in df4.iterrows():
    v=pd.json_normalize(j[1])
    value=len(v)
    key.append(j[0])
    res=dict(zip(key,str(value)))
    Feature.append(res)
df5['Features']=Feature
df5['Feature']=pd.json_normalize(df5['Features'])
df5.drop('Features',axis=1,inplace=True)
df6=pd.json_normalize(data_Kolkata['new_car_specs'])
df7=pd.DataFrame()
for i in df6['top']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df7=pd.concat([df7,a],ignore_index=True)
a=pd.json_normalize(df6['data'])
df=pd.DataFrame()
for i in a:
    df=pd.concat([df,pd.json_normalize(a[i])],ignore_index=True)
df['heading'].value_counts()
df8=df[df['heading'] =='Engine and Transmission']
df9=pd.DataFrame()
for i in df8['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df9=pd.concat([df9,a],ignore_index=True)
df10=df[df['heading'] =='Miscellaneous']
df11=pd.DataFrame()
for i in df10['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df11=pd.concat([df11,a],ignore_index=True)
df12=df[df['heading'] =='Dimensions & Capacity']
df13=pd.DataFrame()
for i in df12['list']:
    a=pd.json_normalize(i)
    keys=[]
    values=[]
    for i in a['key']:
        keys.append(i)
    for i in a['value']:
        values.append(i)
    res=dict(zip(keys,values))
    #res={key:str([values[i] for i in range(len(keys)) if keys[i]==key]) for key in set(keys)}
    a=pd.json_normalize(res)
    df13=pd.concat([df13,a],ignore_index=True)

data_Kolkata=pd.concat([df1,df3,df5,df7,df9,df11,df13],axis=1)
data_Kolkata['City']='Kolkata'

In [47]:
data_Kolkata

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,4825mm,1825mm,1480mm,2775mm,1580mm,1570mm,1625kg,2100kg,NaN,Kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,3429mm,1560mm,1541mm,2348mm,NaN,NaN,770,NaN,185mm,Kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,3991mm,1750,1605,2500,1536,1535,1055,NaN,NaN,Kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,3940 mm,1710 mm,1505 mm,"2,525 mm","1,505 mm","1,503 mm",1020,NaN,NaN,Kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,4385mm,2019mm,1608mm,2603mm,1571mm,1575mm,1660kg,2185kg,NaN,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,4315mm,1822mm,1695mm,2673mm,1560mm,1567mm,1350,1889kg,NaN,Kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolkata

# HANDLING DUPLICATE COLUMNS

In [267]:
column_indices_to_change={44:'RPM'}
data_Kolkata.columns = [column_indices_to_change.get(enum, col) for enum, col in enumerate(data_Kolkata.columns)]
data_Kolkata['RPM']
rpm=[]
for i in data_Kolkata['RPM']:
    try:
        loc=str(i).index('@')
        rpm.append(i[loc+1:])
    except ValueError:
        rpm.append('NA')
data_Kolkata['RPM']=rpm
data_Kolkata=data_Kolkata.loc[:,~data_Kolkata.columns.duplicated()]

In [268]:
data_Kolkata

,it,ft,bt,km,transmission,...,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,City
0,0,Petrol,Sedan,"70,000",Automatic,...,1570mm,1625kg,2100kg,NaN,Kolkata
1,0,Petrol,Hatchback,"23,981",Manual,...,NaN,770,NaN,185mm,Kolkata
2,0,Petrol,SUV,"7,100",Automatic,...,1535,1055,NaN,NaN,Kolkata
3,0,Petrol,Hatchback,"71,574",Manual,...,"1,503 mm",1020,NaN,NaN,Kolkata
4,0,Diesel,SUV,"50,000",Automatic,...,1575mm,1660kg,2185kg,NaN,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,...,1567mm,1350,1889kg,NaN,Kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,...,NaN,NaN,NaN,NaN,Kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata

In [271]:
Car_Dataset=pd.DataFrame()
cities=[Data_Delhi,data_Blore,data_hyderabad,data_Chennai,data_Jaipur,data_Kolkata]
for i in cities:
    Car_Dataset=pd.concat([Car_Dataset,i],ignore_index=True)

In [272]:
Car_Dataset

,it,ft,bt,km,transmission,...,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen,City
0,0,Diesel,SUV,"10,000",Automatic,...,NaN,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,...,NaN,NaN,NaN,NaN,Delhi
2,0,Petrol,SUV,"8,000",Automatic,...,2360kg,NaN,NaN,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,...,1335,1530,1530,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,...,NaN,NaN,NaN,NaN,Delhi
...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,...,1889kg,1560mm,1567mm,NaN,Kolkata
8365,0,Petrol,Hatchback,"1,20,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata
8366,0,Petrol,Sedan,"50,000",Automatic,...,NaN,NaN,NaN,NaN,Kolkata
8367,0,Petrol,Hatchback,"40,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata
8368,0,Diesel,SUV,"1,20,000",Manual,...,NaN,NaN,NaN,NaN,Kolkata

In [275]:
Car_Dataset.to_excel(r'Car_Dataset.xlsx')